from moviepy.editor import AudioFileClip, ImageClip, CompositeVideoClip
import os


def create_shorts_video(audio_path, image_paths, output_path):
    # Load the audio file
    audio = AudioFileClip(audio_path)

    # Load and process images
    clips = []
    duration_per_image = audio.duration / len(image_paths)

    for i, image_path in enumerate(image_paths):
        img_clip = ImageClip(image_path).set_duration(duration_per_image)
        img_clip = img_clip.set_position('center').resize(
            height=1080)  # Resize to 1080p
        clips.append(img_clip)

    # Combine all images into one video
    video = CompositeVideoClip(clips, size=(1920, 1080))
    video = video.set_duration(audio.duration)

    # Set the audio of the video
    final_video = video.set_audio(audio)

    # Write the result to a file
    final_video.write_videofile(output_path, fps=24)


if __name__ == "__main__":
    audio_file = "output.mp3"  # The audio file generated by your Flask app
    image_folder = "images"  # Folder containing images for the video
    output_video = "final_video.mp4"  # Output video file

    # Get list of image files from the folder
    image_files = [os.path.join(image_folder, f) for f in os.listdir(
        image_folder) if f.endswith('.jpg') or f.endswith('.png')]

    create_shorts_video(audio_file, image_files, output_video)
